
/run/numberOfThreads 1
/run/initialize


 
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
 
 
 
 
 
/vis/enable 
/vis/open OGL
/vis/viewer/set/style wireframe
/vis/viewer/set/autoRefresh false
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate
/vis/scene/add/axes
/vis/scene/add/magneticField
